import math
s1,s2=input().split() 
s1=int(s1)
s2=int(s2) 
s3=list(map(int,input().split())) 
x1,y1=input().split()
x1=int(x1)  
y1=int(y1)    
x2,y2=input().split()
x2=int(x2)  
y2=int(y2)
print(end="")  
print(math.gcd(x1,y1))
print(end="")  
print(math.gcd(x2,y2))
